asm_linkage.o: asm_linkage.S x86_desc.h types.h
boot.o: boot.S multiboot.h x86_desc.h types.h idt.h
x86_desc.o: x86_desc.S x86_desc.h types.h
file_sys.o: file_sys.c file_sys.h types.h sys_calls.h lib.h
handlers.o: handlers.c tests.h handlers.h lib.h types.h x86_desc.h \
  keyboard.h rtc.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c lib.h types.h idt.h x86_desc.h asm_linkage.h sys_calls.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h keyboard.h rtc.h paging.h file_sys.h sys_calls.h
keyboard.o: keyboard.c keyboard.h types.h lib.h i8259.h terminal.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h x86_desc.h lib.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h
sys_calls.o: sys_calls.c sys_calls.h types.h file_sys.h terminal.h rtc.h \
  paging.h x86_desc.h lib.h
terminal.o: terminal.c terminal.h types.h lib.h
tests.o: tests.c tests.h i8259.h types.h x86_desc.h lib.h handlers.h \
  paging.h terminal.h file_sys.h sys_calls.h rtc.h
